name: ask_ai
description: "A Flutter-based open-source project for questioning AI with speech."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^7.2.0

dev_dependencies:
  flutter_lints: ^6.0.0